{% set version = "0.4.15" %}

package:
  name: ruamel.ordereddict
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/ruamel.ordereddict/ruamel.ordereddict-{{ version }}.tar.gz
  sha256: d7d9cf8b11e7662deb460260cf062980cd84b87a1d0457132060ab9d44e0a5f4

build:
  number: 0
  skip: true  # [py3k]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - ruamel
  run:
    - python
    - ruamel

test:
  imports:
    - ruamel.ordereddict

about:
  home: https://bitbucket.org/ruamel/ordereddict
  license: MIT
  license_file: LICENSE
  summary: a version of dict that keeps keys in insertion resp. sorted order

extra:
  recipe-maintainers:
    - pelson
    - mwcraig
    - ocefpaf
